export const authSessionResponse = {
  user: {
    id: "user_1",
    email: "teacher@attendease.dev",
    displayName: "Teacher One",
    status: "ACTIVE",
    availableRoles: ["TEACHER"],
    activeRole: "TEACHER",
    sessionId: "session_1",
    platform: "WEB",
    deviceTrust: {
      state: "NOT_REQUIRED",
      lifecycleState: "NOT_APPLICABLE",
      reason: "NOT_STUDENT_ROLE",
      deviceId: null,
      bindingId: null,
    },
  },
  tokens: {
    accessToken: "a".repeat(32),
    accessTokenExpiresAt: "2026-03-15T09:30:00.000Z",
    refreshToken: "b".repeat(32),
    refreshTokenExpiresAt: "2026-04-14T09:30:00.000Z",
  },
} as const

export const liveAttendanceSession = {
  id: "session_1",
  classroomId: "classroom_1",
  classroomCode: "CSE6-MATH-A",
  classroomDisplayTitle: "Mathematics A",
  lectureId: "lecture_1",
  lectureTitle: "Integration Basics",
  lectureDate: "2026-03-15T09:00:00.000Z",
  teacherAssignmentId: "assignment_1",
  mode: "QR_GPS",
  status: "ACTIVE",
  startedAt: "2026-03-15T09:00:00.000Z",
  scheduledEndAt: "2026-03-15T09:15:00.000Z",
  endedAt: null,
  editableUntil: null,
  classId: "class_1",
  classCode: "CSE6",
  classTitle: "Computer Science 6",
  sectionId: "section_1",
  sectionCode: "A",
  sectionTitle: "Section A",
  subjectId: "subject_1",
  subjectCode: "MATH",
  subjectTitle: "Mathematics",
  presentCount: 12,
  absentCount: 3,
  editability: {
    isEditable: false,
    state: "PENDING_SESSION_END",
    endedAt: null,
    editableUntil: null,
  },
} as const

export const manualAttendanceResponse = {
  appliedChangeCount: 2,
  session: {
    id: "session_1",
    classroomId: "classroom_1",
    lectureId: "lecture_1",
    teacherAssignmentId: "assignment_1",
    mode: "QR_GPS",
    status: "ENDED",
    startedAt: "2026-03-15T09:00:00.000Z",
    scheduledEndAt: "2026-03-15T09:15:00.000Z",
    endedAt: "2026-03-15T09:15:00.000Z",
    editableUntil: "2026-03-15T18:00:00.000Z",
    durationSeconds: 900,
    anchorType: "TEACHER_SELECTED",
    anchorLatitude: 28.6139,
    anchorLongitude: 77.209,
    anchorLabel: "Room 101",
    gpsRadiusMeters: 120,
    qrRotationWindowSeconds: 15,
    bluetoothRotationWindowSeconds: null,
    blePublicId: null,
    bleProtocolVersion: null,
    rosterSnapshotCount: 15,
    presentCount: 13,
    absentCount: 2,
    currentQrPayload: null,
    currentQrExpiresAt: null,
    classroomCode: "CSE6-MATH-A",
    classroomDisplayTitle: "Mathematics A",
    lectureTitle: "Integration Basics",
    lectureDate: "2026-03-15T09:00:00.000Z",
    teacherId: "teacher_1",
    teacherDisplayName: "Teacher One",
    teacherEmail: "teacher@attendease.dev",
    semesterCode: "SEM-6",
    semesterTitle: "Semester 6",
    classCode: "CSE6",
    classTitle: "Computer Science 6",
    sectionCode: "A",
    sectionTitle: "Section A",
    subjectCode: "MATH",
    subjectTitle: "Mathematics",
    editability: {
      isEditable: true,
      state: "OPEN",
      endedAt: "2026-03-15T09:15:00.000Z",
      editableUntil: "2026-03-15T18:00:00.000Z",
    },
    suspiciousAttemptCount: 0,
    blockedUntrustedDeviceCount: 0,
    locationValidationFailureCount: 0,
    bluetoothValidationFailureCount: 0,
    revokedDeviceAttemptCount: 0,
  },
  students: [
    {
      attendanceRecordId: "record_1",
      enrollmentId: "enrollment_1",
      studentId: "student_1",
      studentDisplayName: "Student One",
      studentEmail: "student.one@attendease.dev",
      studentRollNumber: "23CS001",
      status: "PRESENT",
      markedAt: "2026-03-15T09:16:00.000Z",
    },
    {
      attendanceRecordId: "record_2",
      enrollmentId: "enrollment_2",
      studentId: "student_2",
      studentDisplayName: "Student Two",
      studentEmail: "student.two@attendease.dev",
      studentRollNumber: "23CS002",
      status: "ABSENT",
      markedAt: null,
    },
  ],
} as const
