import { webTheme } from "@attendease/ui-web"

export const qrShellStyles = {
  grid: {
    display: "grid",
    gap: 20,
  },
  hero: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 28,
    display: "grid",
    gap: 18,
  },
  projectorHero: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    background: webTheme.colors.surfaceMuted,
    padding: 32,
    display: "grid",
    gap: 22,
  },
  heroTopRow: {
    display: "grid",
    gap: 18,
    gridTemplateColumns: "minmax(0, 1.25fr) minmax(280px, 0.75fr)",
    alignItems: "start",
  },
  statPillRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap" as const,
    justifyContent: "flex-end",
  },
  statPill: {
    borderRadius: 999,
    padding: "10px 16px",
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceTint,
    display: "grid",
    gap: 4,
    minWidth: 132,
  },
  pillLabel: {
    margin: 0,
    color: webTheme.colors.textSubtle,
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  pillValue: {
    margin: 0,
    color: webTheme.colors.text,
    fontSize: 20,
    fontWeight: 700,
  },
  stageGrid: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "minmax(0, 1.1fr) minmax(320px, 0.9fr)",
    alignItems: "start",
  },
  qrStage: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 24,
    display: "grid",
    gap: 18,
  },
  projectorStage: {
    borderRadius: webTheme.radius.card,
    border: `2px solid ${webTheme.colors.borderStrong}`,
    background: webTheme.colors.surfaceMuted,
    padding: 36,
    display: "grid",
    gap: 22,
  },
  qrFrame: {
    display: "grid",
    placeItems: "center",
    minHeight: 360,
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: "#FFFFFF",
    padding: 24,
  },
  projectorQrFrame: {
    display: "grid",
    placeItems: "center",
    minHeight: 600,
    borderRadius: webTheme.radius.card,
    border: `2px solid ${webTheme.colors.borderStrong}`,
    background: "#FFFFFF",
    padding: 40,
  },
  qrImage: {
    width: "100%",
    maxWidth: 360,
    aspectRatio: "1 / 1",
    objectFit: "contain" as const,
  },
  projectorQrImage: {
    width: "100%",
    maxWidth: 560,
    aspectRatio: "1 / 1",
    objectFit: "contain" as const,
  },
  actionRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: webTheme.radius.button,
    border: "none",
    background: webTheme.colors.accent,
    color: "#0D0D0D",
    fontWeight: 600,
    fontSize: 14,
    padding: "11px 20px",
    textDecoration: "none",
    cursor: "pointer",
    transition: `all ${webTheme.animation.fast}`,
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.border}`,
    background: "transparent",
    color: webTheme.colors.textMuted,
    fontWeight: 500,
    fontSize: 14,
    padding: "11px 18px",
    textDecoration: "none",
    cursor: "pointer",
    transition: `all ${webTheme.animation.fast}`,
  },
  dangerButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: webTheme.radius.button,
    border: "none",
    background: webTheme.colors.dangerSoft,
    color: webTheme.colors.danger,
    fontWeight: 600,
    fontSize: 14,
    padding: "11px 18px",
    cursor: "pointer",
    transition: `all ${webTheme.animation.fast}`,
  },
  rosterColumn: {
    display: "grid",
    gap: 20,
  },
  rosterSummaryRow: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  rosterSummaryCard: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceTint,
    padding: 16,
  },
  rosterScroll: {
    display: "grid",
    gap: 10,
    maxHeight: 420,
    overflowY: "auto" as const,
    paddingRight: 6,
  },
  rosterItem: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 14,
  },
  detailsGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  detailCard: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceTint,
    padding: 16,
  },
  projectorFooterGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  },
  metaText: {
    margin: 0,
    color: webTheme.colors.textMuted,
    lineHeight: 1.6,
    fontSize: 14,
  },
  statusBanner: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.dangerBorder}`,
    background: webTheme.colors.dangerSoft,
    color: webTheme.colors.danger,
    padding: 16,
    fontSize: 14,
  },
} as const
