import { webTheme } from "@attendease/ui-web"

export const qrShellStyles = {
  grid: {
    display: "grid",
    gap: 16,
    height: "calc(100vh - 100px)",
    gridTemplateRows: "auto auto 1fr",
    overflow: "hidden",
  },
  hero: {
    borderRadius: 16,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    boxShadow: "var(--ae-card-shadow)",
    padding: "20px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    flexWrap: "wrap" as const,
    position: "relative" as const,
    overflow: "hidden" as const,
  },
  projectorHero: {
    padding: "16px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap" as const,
    borderRadius: 16,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    boxShadow: "var(--ae-card-shadow)",
    position: "relative" as const,
    overflow: "hidden" as const,
  },
  heroTopRow: {
    display: "grid",
    gap: 18,
    gridTemplateColumns: "minmax(0, 1.25fr) minmax(280px, 0.75fr)",
    alignItems: "start",
  },
  statPillRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  statPill: {
    borderRadius: 12,
    padding: "8px 16px",
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    display: "grid",
    gap: 2,
    minWidth: 110,
  },
  pillLabel: {
    margin: 0,
    color: webTheme.colors.textSubtle,
    fontSize: 10,
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
  },
  pillValue: {
    margin: 0,
    color: webTheme.colors.text,
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  },
  stageGrid: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: "1fr 320px",
    alignItems: "stretch",
    minHeight: 0,
    overflow: "hidden",
  },
  qrStage: {
    borderRadius: 16,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    boxShadow: "var(--ae-card-shadow)",
    padding: 24,
    display: "grid",
    gap: 20,
  },
  projectorStage: {
    borderRadius: 16,
    border: `2px solid ${webTheme.colors.borderStrong}`,
    background: webTheme.colors.surfaceMuted,
    padding: 36,
    display: "grid",
    gap: 22,
  },
  qrFrame: {
    display: "grid",
    placeItems: "center",
    borderRadius: 16,
    background: "#FFFFFF",
    padding: 16,
    minHeight: 0,
    flex: 1,
    overflow: "hidden",
  },
  projectorQrFrame: {
    display: "grid",
    placeItems: "center",
    borderRadius: 16,
    background: "#FFFFFF",
    padding: 24,
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  qrImage: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain" as const,
  },
  projectorQrImage: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain" as const,
  },
  actionRow: {
    display: "flex",
    gap: 10,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    flexWrap: "wrap" as const,
    flexShrink: 0,
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    border: "none",
    background: webTheme.gradients.accentButton,
    color: "#fff",
    fontWeight: 600,
    fontSize: 14,
    padding: "10px 20px",
    textDecoration: "none",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: webTheme.shadow.glow,
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    border: "1px solid var(--ae-card-border)",
    background: "transparent",
    color: webTheme.colors.textMuted,
    fontWeight: 500,
    fontSize: 13,
    padding: "10px 18px",
    textDecoration: "none",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  dangerButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    border: `1px solid ${webTheme.colors.dangerBorder}`,
    background: webTheme.colors.dangerSoft,
    color: webTheme.colors.danger,
    fontWeight: 600,
    fontSize: 13,
    padding: "10px 18px",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  confirmEndGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px 6px 14px",
    borderRadius: 12,
    border: `1px solid ${webTheme.colors.dangerBorder}`,
    background: webTheme.colors.dangerSoft,
  },
  rosterColumn: {
    display: "grid",
    gap: 14,
  },
  rosterSummaryRow: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  rosterSummaryCard: {
    borderRadius: 12,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    padding: 14,
  },
  rosterScroll: {
    display: "grid",
    gap: 6,
    maxHeight: 350,
    overflowY: "auto" as const,
    paddingRight: 4,
  },
  rosterItem: {
    borderRadius: 10,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    padding: 12,
  },
  detailsGrid: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  },
  detailCard: {
    borderRadius: 12,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    padding: 14,
  },
  projectorFooterGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  },
  metaText: {
    margin: 0,
    color: webTheme.colors.textMuted,
    lineHeight: 1.5,
    fontSize: 13,
  },
  statusBanner: {
    borderRadius: 12,
    border: `1px solid ${webTheme.colors.dangerBorder}`,
    background: webTheme.colors.dangerSoft,
    color: webTheme.colors.danger,
    padding: 14,
    fontSize: 14,
  },
} as const
