import { webTheme } from "@attendease/ui-web"

export const qrShellStyles = {
  grid: {
    display: "grid",
    gap: 20,
  },
  hero: {
    borderRadius: 30,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    background:
      "radial-gradient(circle at top left, rgba(234, 91, 42, 0.16), transparent 42%), linear-gradient(180deg, #fffaf2 0%, #f4eadc 100%)",
    padding: 28,
    display: "grid",
    gap: 18,
  },
  projectorHero: {
    borderRadius: 34,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    background:
      "radial-gradient(circle at top left, rgba(234, 91, 42, 0.22), transparent 38%), linear-gradient(180deg, #fff7ee 0%, #efe1d0 100%)",
    padding: 32,
    display: "grid",
    gap: 22,
  },
  heroTopRow: {
    display: "grid",
    gap: 18,
    gridTemplateColumns: "minmax(0, 1.25fr) minmax(280px, 0.75fr)",
    alignItems: "start",
  },
  statPillRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap" as const,
    justifyContent: "flex-end",
  },
  statPill: {
    borderRadius: 999,
    padding: "10px 14px",
    border: `1px solid ${webTheme.colors.borderStrong}`,
    background: "rgba(255,255,255,0.9)",
    display: "grid",
    gap: 4,
    minWidth: 132,
  },
  pillLabel: {
    margin: 0,
    color: webTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  pillValue: {
    margin: 0,
    color: webTheme.colors.primary,
    fontSize: 20,
    fontWeight: 800,
  },
  stageGrid: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "minmax(0, 1.1fr) minmax(320px, 0.9fr)",
    alignItems: "start",
  },
  qrStage: {
    borderRadius: 28,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    background: "linear-gradient(180deg, rgba(255,250,242,0.98) 0%, rgba(244,234,220,0.98) 100%)",
    padding: 24,
    display: "grid",
    gap: 18,
  },
  projectorStage: {
    borderRadius: 40,
    border: `2px solid ${webTheme.colors.borderStrong}`,
    background: "linear-gradient(180deg, rgba(255,250,242,1) 0%, rgba(244,234,220,1) 100%)",
    padding: 36,
    display: "grid",
    gap: 22,
  },
  qrFrame: {
    display: "grid",
    placeItems: "center",
    minHeight: 360,
    borderRadius: 30,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 24,
  },
  projectorQrFrame: {
    display: "grid",
    placeItems: "center",
    minHeight: 600,
    borderRadius: 40,
    border: `2px solid ${webTheme.colors.borderStrong}`,
    background: webTheme.colors.surfaceRaised,
    padding: 40,
  },
  qrImage: {
    width: "100%",
    maxWidth: 360,
    aspectRatio: "1 / 1",
    objectFit: "contain" as const,
  },
  projectorQrImage: {
    width: "100%",
    maxWidth: 560,
    aspectRatio: "1 / 1",
    objectFit: "contain" as const,
  },
  actionRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: webTheme.radius.button,
    border: "none",
    background: webTheme.colors.primary,
    color: webTheme.colors.primaryContrast,
    fontWeight: 700,
    padding: "13px 18px",
    textDecoration: "none",
    cursor: "pointer",
    boxShadow: "0 14px 28px rgba(15, 17, 21, 0.14)",
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    color: webTheme.colors.text,
    fontWeight: 700,
    padding: "13px 18px",
    textDecoration: "none",
    cursor: "pointer",
  },
  dangerButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: webTheme.radius.button,
    border: "none",
    background: webTheme.colors.danger,
    color: webTheme.colors.primaryContrast,
    fontWeight: 700,
    padding: "13px 18px",
    cursor: "pointer",
  },
  rosterColumn: {
    display: "grid",
    gap: 20,
  },
  rosterSummaryRow: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  rosterSummaryCard: {
    borderRadius: 18,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceMuted,
    padding: 16,
  },
  rosterScroll: {
    display: "grid",
    gap: 10,
    maxHeight: 420,
    overflowY: "auto" as const,
    paddingRight: 6,
  },
  rosterItem: {
    borderRadius: 18,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 14,
  },
  detailsGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  detailCard: {
    borderRadius: 18,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 16,
  },
  projectorFooterGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  },
  metaText: {
    margin: 0,
    color: webTheme.colors.textMuted,
    lineHeight: 1.6,
  },
  statusBanner: {
    borderRadius: 18,
    border: `1px solid ${webTheme.colors.dangerBorder}`,
    background: webTheme.colors.dangerSoft,
    color: webTheme.colors.danger,
    padding: 16,
  },
} as const
