import { webTheme } from "@attendease/ui-web"

export const workflowStyles = {
  grid: {
    display: "grid",
    gap: 24,
  },
  twoColumn: {
    display: "grid",
    gap: 24,
    gridTemplateColumns: "minmax(0, 1.15fr) minmax(320px, 0.85fr)",
  },
  formGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  input: {
    width: "100%",
    borderRadius: 10,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "10px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceMuted,
    color: webTheme.colors.text,
    outline: "none",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },
  textarea: {
    width: "100%",
    minHeight: 120,
    borderRadius: 10,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "10px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceMuted,
    color: webTheme.colors.text,
    resize: "vertical" as const,
    outline: "none",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },
  buttonRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  primaryButton: {
    border: "none",
    borderRadius: 10,
    padding: "10px 20px",
    background: webTheme.gradients.accentButton,
    color: "#fff",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    textDecoration: "none",
    transition: "all 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
    boxShadow: webTheme.shadow.glow,
  },
  secondaryButton: {
    border: `1px solid ${webTheme.colors.borderStrong}`,
    borderRadius: 10,
    padding: "10px 18px",
    background: "transparent",
    color: webTheme.colors.textMuted,
    fontWeight: 500,
    fontSize: 14,
    cursor: "pointer",
    textDecoration: "none",
    transition: "all 0.15s ease",
  },
  dangerButton: {
    border: "none",
    borderRadius: 10,
    padding: "10px 18px",
    background: webTheme.colors.dangerSoft,
    color: webTheme.colors.danger,
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    padding: "4px 12px",
    background: "rgba(167, 139, 250, 0.08)",
    border: `1px solid rgba(167, 139, 250, 0.15)`,
    color: webTheme.colors.textMuted,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.02em",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
  },
  stateCard: {
    borderRadius: webTheme.radius.card,
    border: "1px dashed var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    padding: 18,
    color: webTheme.colors.textMuted,
    fontSize: 14,
  },
  rowCard: {
    borderRadius: 16,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    padding: 20,
    boxShadow: "var(--ae-card-shadow)",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    position: "relative" as const,
    overflow: "hidden" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: 14,
  },
  th: {
    textAlign: "left" as const,
    padding: "10px 16px",
    color: webTheme.colors.accent,
    opacity: 0.7,
    fontSize: 11,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    fontWeight: 600,
    borderBottom: `1px solid ${webTheme.colors.border}`,
    background: "var(--ae-th-bg)",
  },
  td: {
    padding: "12px 16px",
    borderBottom: "1px solid var(--ae-card-border, rgba(167,139,250,0.12))",
    verticalAlign: "middle" as const,
    color: webTheme.colors.text,
    fontSize: 14,
  },
  linkGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  },
  linkCard: {
    display: "block",
    borderRadius: 16,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    padding: 16,
    textDecoration: "none",
    color: "inherit",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    boxShadow: webTheme.shadow.card,
  },
  cardGrid: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
  },
  summaryGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
  },
  summaryMetric: {
    borderRadius: 14,
    border: "1px solid var(--ae-card-border)",
    background: "var(--ae-card-surface)",
    padding: 16,
    boxShadow: "var(--ae-card-shadow)",
    position: "relative" as const,
    overflow: "hidden" as const,
  },
} as const
