import { webTheme } from "@attendease/ui-web"

export const workflowStyles = {
  grid: {
    display: "grid",
    gap: 20,
  },
  twoColumn: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "minmax(0, 1.15fr) minmax(320px, 0.85fr)",
  },
  formGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  input: {
    width: "100%",
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "13px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceRaised,
    color: webTheme.colors.text,
  },
  textarea: {
    width: "100%",
    minHeight: 124,
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "13px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceRaised,
    color: webTheme.colors.text,
    resize: "vertical" as const,
  },
  buttonRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  primaryButton: {
    border: "none",
    borderRadius: webTheme.radius.button,
    padding: "13px 18px",
    background: webTheme.colors.primary,
    color: webTheme.colors.primaryContrast,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 14px 28px rgba(15, 17, 21, 0.14)",
  },
  secondaryButton: {
    border: `1px solid ${webTheme.colors.border}`,
    borderRadius: webTheme.radius.button,
    padding: "13px 18px",
    background: webTheme.colors.surfaceRaised,
    color: webTheme.colors.text,
    fontWeight: 700,
    cursor: "pointer",
  },
  dangerButton: {
    border: "none",
    borderRadius: webTheme.radius.button,
    padding: "13px 18px",
    background: webTheme.colors.danger,
    color: webTheme.colors.primaryContrast,
    fontWeight: 700,
    cursor: "pointer",
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    padding: "8px 12px",
    background: webTheme.colors.surfaceTint,
    border: `1px solid ${webTheme.colors.border}`,
    color: webTheme.colors.primary,
    fontSize: 13,
    fontWeight: 700,
  },
  stateCard: {
    borderRadius: 24,
    border: `1px dashed ${webTheme.colors.borderStrong}`,
    background: webTheme.colors.surfaceMuted,
    padding: 18,
    color: webTheme.colors.textMuted,
  },
  rowCard: {
    borderRadius: 24,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 16,
    boxShadow: webTheme.shadow.card,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  th: {
    textAlign: "left" as const,
    padding: "12px 10px",
    color: webTheme.colors.textMuted,
    fontSize: 12,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    borderBottom: `1px solid ${webTheme.colors.border}`,
  },
  td: {
    padding: "14px 10px",
    borderBottom: `1px solid ${webTheme.colors.surfaceMuted}`,
    verticalAlign: "top" as const,
    color: webTheme.colors.text,
  },
  linkGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  },
  linkCard: {
    display: "block",
    borderRadius: 24,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceTint,
    padding: 16,
    textDecoration: "none",
    color: "inherit",
  },
  cardGrid: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
  },
  summaryGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  },
  summaryMetric: {
    borderRadius: 20,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceTint,
    padding: 14,
  },
} as const
