import { webTheme } from "@attendease/ui-web"

export const workflowStyles = {
  grid: {
    display: "grid",
    gap: 20,
  },
  twoColumn: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "minmax(0, 1.15fr) minmax(320px, 0.85fr)",
  },
  formGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  input: {
    width: "100%",
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "12px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceMuted,
    color: webTheme.colors.text,
    outline: "none",
  },
  textarea: {
    width: "100%",
    minHeight: 124,
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "12px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceMuted,
    color: webTheme.colors.text,
    resize: "vertical" as const,
    outline: "none",
  },
  buttonRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  primaryButton: {
    border: "none",
    borderRadius: webTheme.radius.button,
    padding: "11px 20px",
    background: webTheme.colors.accent,
    color: "#0D0D0D",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    textDecoration: "none",
    transition: `all ${webTheme.animation.fast}`,
  },
  secondaryButton: {
    border: `1px solid ${webTheme.colors.border}`,
    borderRadius: webTheme.radius.button,
    padding: "11px 18px",
    background: "transparent",
    color: webTheme.colors.textMuted,
    fontWeight: 500,
    fontSize: 14,
    cursor: "pointer",
    textDecoration: "none",
    transition: `all ${webTheme.animation.fast}`,
  },
  dangerButton: {
    border: "none",
    borderRadius: webTheme.radius.button,
    padding: "11px 18px",
    background: webTheme.colors.dangerSoft,
    color: webTheme.colors.danger,
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    padding: "5px 12px",
    background: webTheme.colors.surfaceTint,
    border: `1px solid ${webTheme.colors.border}`,
    color: webTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: 600,
  },
  stateCard: {
    borderRadius: webTheme.radius.card,
    border: `1px dashed ${webTheme.colors.borderStrong}`,
    background: webTheme.colors.surfaceMuted,
    padding: 18,
    color: webTheme.colors.textMuted,
    fontSize: 14,
  },
  rowCard: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 20,
    transition: `all ${webTheme.animation.normal} ${webTheme.animation.easing}`,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  th: {
    textAlign: "left" as const,
    padding: "12px 10px",
    color: webTheme.colors.textSubtle,
    fontSize: 11,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    fontWeight: 600,
    borderBottom: `1px solid ${webTheme.colors.border}`,
  },
  td: {
    padding: "14px 10px",
    borderBottom: `1px solid ${webTheme.colors.border}`,
    verticalAlign: "top" as const,
    color: webTheme.colors.text,
    fontSize: 14,
  },
  linkGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  },
  linkCard: {
    display: "block",
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceTint,
    padding: 16,
    textDecoration: "none",
    color: "inherit",
    transition: `all ${webTheme.animation.normal} ${webTheme.animation.easing}`,
  },
  cardGrid: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))",
  },
  summaryGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  },
  summaryMetric: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceTint,
    padding: 16,
  },
} as const
