ALTER TYPE "AdminActionType"
ADD VALUE IF NOT EXISTS 'SEMESTER_ARCHIVE';

ALTER TYPE "AdminActionType"
ADD VALUE IF NOT EXISTS 'CLASSROOM_ARCHIVE';

ALTER TYPE "AdminActionType"
ADD VALUE IF NOT EXISTS 'CLASSROOM_STUDENT_REMOVE';
