export const teacherAnalyticsStyles = {
  grid: {
    display: "grid",
    gap: 20,
  },
  split: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
  },
  compactGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  card: {
    borderRadius: 18,
    border: "1px solid #dbe4f0",
    background: "#ffffff",
    padding: 16,
  },
  state: {
    borderRadius: 18,
    border: "1px dashed #cbd5e1",
    background: "#f8fafc",
    padding: 16,
    color: "#475569",
  },
  bannerBase: {
    borderRadius: 16,
    padding: "12px 14px",
    fontWeight: 600,
  },
  formGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  input: {
    width: "100%",
    borderRadius: 14,
    border: "1px solid #cbd5e1",
    padding: "12px 14px",
    fontSize: 14,
    background: "#ffffff",
  },
  textarea: {
    width: "100%",
    minHeight: 124,
    borderRadius: 14,
    border: "1px solid #cbd5e1",
    padding: "12px 14px",
    fontSize: 14,
    background: "#ffffff",
    resize: "vertical" as const,
  },
  buttonRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  primaryButton: {
    border: "none",
    borderRadius: 14,
    padding: "12px 16px",
    background: "#1d4ed8",
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
  },
  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: 14,
    padding: "12px 16px",
    background: "#ffffff",
    color: "#0f172a",
    fontWeight: 700,
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  th: {
    textAlign: "left" as const,
    padding: "12px 10px",
    color: "#475569",
    fontSize: 12,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    borderBottom: "1px solid #e2e8f0",
  },
  td: {
    padding: "14px 10px",
    borderBottom: "1px solid #eef2f7",
    verticalAlign: "top" as const,
    color: "#0f172a",
  },
} as const
