import { webTheme } from "@attendease/ui-web"

export const teacherAnalyticsStyles = {
  grid: {
    display: "grid",
    gap: 20,
  },
  split: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
  },
  compactGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  card: {
    borderRadius: webTheme.radius.card,
    border: `1px solid ${webTheme.colors.border}`,
    background: webTheme.colors.surfaceRaised,
    padding: 16,
  },
  state: {
    borderRadius: webTheme.radius.card,
    border: `1px dashed ${webTheme.colors.borderStrong}`,
    background: webTheme.colors.surfaceMuted,
    padding: 16,
    color: webTheme.colors.textMuted,
  },
  bannerBase: {
    borderRadius: webTheme.radius.button,
    padding: "12px 14px",
    fontWeight: 600,
  },
  formGrid: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  input: {
    width: "100%",
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "12px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceMuted,
    color: webTheme.colors.text,
    outline: "none",
  },
  textarea: {
    width: "100%",
    minHeight: 124,
    borderRadius: webTheme.radius.button,
    border: `1px solid ${webTheme.colors.borderStrong}`,
    padding: "12px 14px",
    fontSize: 14,
    background: webTheme.colors.surfaceMuted,
    color: webTheme.colors.text,
    resize: "vertical" as const,
    outline: "none",
  },
  buttonRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  primaryButton: {
    border: "none",
    borderRadius: webTheme.radius.button,
    padding: "12px 16px",
    background: webTheme.colors.accent,
    color: "#0D0D0D",
    fontWeight: 700,
    cursor: "pointer",
  },
  secondaryButton: {
    border: `1px solid ${webTheme.colors.border}`,
    borderRadius: webTheme.radius.button,
    padding: "12px 16px",
    background: "transparent",
    color: webTheme.colors.textMuted,
    fontWeight: 700,
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  th: {
    textAlign: "left" as const,
    padding: "12px 10px",
    color: webTheme.colors.textSubtle,
    fontSize: 12,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    borderBottom: `1px solid ${webTheme.colors.border}`,
  },
  td: {
    padding: "14px 10px",
    borderBottom: `1px solid ${webTheme.colors.border}`,
    verticalAlign: "top" as const,
    color: webTheme.colors.text,
  },
} as const
